### ISSUE TITLE
Curious about the LDAP connection package

### ISSUE THREAD

**Issue by rwkarg** [OctopusDeploy/LdapAuthenticationProvider#20]
I'm curious on the reason for using https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard over https://www.nuget.org/packages/System.DirectoryServices.Protocols

From the Novel.Directory.Ldap.NETStandard README:

> The library is originally coming from Novell (https://www.novell.com/developer/ndk/ldap_libraries_for_c_sharp.html) - really old code base - looks like a tool-based conversion from Java - this is the original java code repo http://www.openldap.org/devel/gitweb.cgi?p=openldap-jldap.git;a=summary (first commit in that repo is from 2000 :)) - which explains some of the weirdness of the code base.

I don't have any specific reason to say that either package would be "wrong" but I am curious as to the decision to use the Novell library (looks like Novell last updated the original one in 2009, though the NETStandard one is in active development) over the System package (which is also in active development).

**Comment by tunger** [comment]
When I started developing the extension in May 2020, the Novell NETStandard library was the best option for .NET Core and Linux support, and it works.
System.DirectoryServices.Protocols only added Linux support with the release of .NET 5 (https://github.com/dotnet/runtime/issues/36888).

**Comment by rwkarg** [comment]
Thanks for the info!

We have a really old (Octopus 2.X timeframe) LDAP provider for Octopus that needs to be updated and it uses System.DirectoryServices.Protocols so that's what I was expecting.

After spending more time with the Novell NETStandard library more, it's less scary than the README comment made it seem.
