### ISSUE TITLE
LDAP Anonymous Bind isn't supported

### ISSUE THREAD

**Issue by rwkarg** [OctopusDeploy/LdapAuthenticationProvider#44]
LDAP can support anonymous Bind, but the provider currently throws a NullReferenceException because it expects the password to be non-null.

This can be supported with the following change:
```
con.Bind(ldapConfiguration.Value.GetConnectUsername(), ldapConfiguration.Value.GetConnectPassword().Value);
```

to (note the `?` on `GetConnectPassword`):

```
con.Bind(ldapConfiguration.Value.GetConnectUsername(), ldapConfiguration.Value.GetConnectPassword()?.Value);
```
as shown [this PR](https://github.com/OctopusDeploy/LdapAuthenticationProvider/pull/22/files#diff-ac142b4482fdaa11f0e60e37e6d678c9e6307bbd314f6549038eaae8067bfdd8R44)

`Bind` will successfully treat an empty/null password as an anonymous Bind attempt.

**Comment by ryangribble** [comment]
Fixed... see https://github.com/OctopusDeploy/Issues/issues/6987
