### ISSUE TITLE
Transfer ownership and assign copyright to OctopusDeploy

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/LdapAuthenticationProvider#7]
As discussed on email, we would like to make this an official part of the product. It will stay open source as per the other providers.

**Comment by tunger** [comment]
I agree and I am happy to transfer the ownership and assign the copyright to OctopusDeploy. I am excited that this becomes a part of the product!

**Comment by droyad** [comment]
Done. Thanks for the contribution!
